[package]
name = "shootsh"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.43"
crossterm = "0.27"
rand = "0.9.2"
ratatui = "0.30.0"
rusqlite = { version = "0.38.0", features = ["bundled"] }
